name: Schedule

on:
  schedule:
    - cron: "*/10 7-18 * * *"
    
    
jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4 
    - uses: actions/setup-python@v5
      with:
          python-version: '3.10.8'
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4

    - name: Run Python script
      run: python Weather.py
