name: Schedule

on:
  schedule:
    - cron: "*/10 7-18 * * 1-5"
    
    
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Set up environment variables
        run: |
             echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
        env:
             GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Replace with your requirements file name, if necessary

      - name: Run Python script
        run: python Weather.py # Replace with your script name
